### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined due to race condition

### ISSUE THREAD

**Issue by ismriv** [kurttheviking/bluecache#11]
It looks like there's a race condition when retrieving items from the cache if the item expires between the key it's [checked for existence](https://github.com/kurttheviking/bluecache/blob/1ff0a1d7b8aa7069315a8d22a0be3f190bb8ef61/lib/Bluecache.js#L55) and the key is [retrieved](https://github.com/kurttheviking/bluecache/blob/1ff0a1d7b8aa7069315a8d22a0be3f190bb8ef61/lib/Bluecache.js#L57), leading to a TypeError since the item will not exist in the cache and cannot therefore cannot read its property `value`.

    if (lrucache.has(finalKey)) {
      emit(finalKey, true);
      return lrucache.get(finalKey).value;
    }

A way to avoid this issue could be changing that block to the following:

    const hit = lrucache.get(finalKey);
    if (hit) {
      emit(finalKey, true);
      return hit.value;
    }

What are your thoughts?

**Comment by kurttheviking** [comment]
@ismriv i like that approach; i can patch it myself but if you have a PR ready I can merge that instead
