### ISSUE TITLE
Extend API with function to reset cache

### ISSUE THREAD

**Issue by ismriv** [kurttheviking/bluecache#12]
It would be great if `bluecache` exposed a function to reset the cache that simply calls the underlying reset function of `lru-cache`, so that third-party code doesn't need to do that through the `_lrucache` property as in the following example:

    myBlueCache._lrucache.reset();

I can submit a pull request if this sounds reasonable.

**Comment by kurttheviking** [comment]
@ismriv sounds good to me; feel free to PR

**Comment by kurttheviking** [comment]
thanks @ismriv &ndash; shipped as `v4.1.0`!
